name: Java CI/CD to Digital Ocean

on:
  push:
    branches: [ main ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Check out the repository 
      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Or your desired Java version
          distribution: 'temurin'  

      - name: Build with Maven 
        run: mvn -f inventory-service/pom.xml clean test 
